title: Weekly Assignments
description: Coursework site
theme: jekyll-theme-primer

exclude:
  - node_modules"
  - "**/node_modules"
  - "**/package.json"
  - "**/package-lock.json"
  - "**/yarn.lock"
